word_list = ["electroencefalografista",
            "transustanciacion",
            "caleidoscopio",
            "hipopotomonstrosesquipedaliofobia",
            "clavicembalo",
            "ovoviviparo",
            "arteriosclerosis",
            "esternocleidomastoide",
            "idiosincrasia",
            "vicisitud",
            "sucinto",
            "convalecencia",
            "beneficencia",
            "inextricable",
            "quincunce",
            "zafiro",
            "jolgorio",
            "xilófono"]

